/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/devices": {
    /**
     * Get all devices.
     * @description List all devices.
     */
    get: operations["listDevicesRoute"];
    /**
     * Register a new device
     * @description Register a new device.
     */
    post: operations["registerDeviceRoute"];
  };
  "/devices/{deviceId}": {
    /**
     * Get a device by its ID.
     * @description Get a device by its ID.
     */
    get: operations["getDeviceRoute"];
    /**
     * Update a device by its ID.
     * @description Update a device by its ID.
     */
    put: operations["updateDeviceRoute"];
  };
  "/health": {
    /**
     * Health
     * @description Endpoint to determine the health of the API.
     */
    get: operations["health"];
  };
  "/devices/{deviceId}/ws/token": {
    /**
     * Get a token to be used to connect to the websocket.
     * @description Returns a token that can be used to authenticate the edge device to the API.
     */
    get: operations["getDeviceServerWebsocketToken"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * CarlosDevice
     * @description Represents an existing device.
     */
    CarlosDevice: {
      /**
       * Displayname
       * @description The name of the device that is displayed to the user.
       */
      displayName: string;
      /**
       * Description
       * @description A description of the device for the user.
       */
      description?: string | null;
      /**
       * Deviceid
       * Format: uuid
       * @description The unique identifier of the device.
       */
      deviceId: string;
      /**
       * Registeredat
       * Format: date-time
       * @description The date and time when the device was registered.
       */
      registeredAt: string;
      /**
       * Lastseenat
       * @description The date and time when the device was last seen.
       */
      lastSeenAt: string | null;
      /**
       * Isonline
       * @description Check if the device is online.
       */
      isOnline: boolean;
    };
    /**
     * CarlosDeviceCreate
     * @description Allow you to create a new device.
     */
    CarlosDeviceCreate: {
      /**
       * Displayname
       * @description The name of the device that is displayed to the user.
       */
      displayName: string;
      /**
       * Description
       * @description A description of the device for the user.
       */
      description?: string | null;
    };
    /**
     * CarlosDeviceUpdate
     * @description Allows you to update the device information.
     */
    CarlosDeviceUpdate: {
      /**
       * Displayname
       * @description The name of the device that is displayed to the user.
       */
      displayName: string;
      /**
       * Description
       * @description A description of the device for the user.
       */
      description?: string | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * HealthResponse
     * @description Defines the status of the API.
     */
    HealthResponse: {
      status: components["schemas"]["HealthStatus"];
      /**
       * Message
       * @description A message about the status of the API.
       */
      message: string;
    };
    /**
     * HealthStatus
     * @description The status of the API.
     * @enum {string}
     */
    HealthStatus: "ok" | "no_db_connection" | "error";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get all devices.
   * @description List all devices.
   */
  listDevicesRoute: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CarlosDevice"][];
        };
      };
    };
  };
  /**
   * Register a new device
   * @description Register a new device.
   */
  registerDeviceRoute: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CarlosDeviceCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CarlosDevice"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get a device by its ID.
   * @description Get a device by its ID.
   */
  getDeviceRoute: {
    parameters: {
      path: {
        /** @description The unique identifier of the device. */
        device_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CarlosDevice"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Update a device by its ID.
   * @description Update a device by its ID.
   */
  updateDeviceRoute: {
    parameters: {
      path: {
        /** @description The unique identifier of the device. */
        device_id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CarlosDeviceUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CarlosDevice"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Health
   * @description Endpoint to determine the health of the API.
   */
  health: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  /**
   * Get a token to be used to connect to the websocket.
   * @description Returns a token that can be used to authenticate the edge device to the API.
   */
  getDeviceServerWebsocketToken: {
    parameters: {
      path: {
        /** @description The unique identifier of the device. */
        deviceId: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "text/plain": string;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
