lib/py_dev_dependencies:
  language: python
lib/py_edge_interface:
  language: python
lib/py_monorepo_manager:
  language: python
  makefile:
    boilerplate:
    - poetry run monorepo_manager all
services/api:
  language: python
