lib/py_carlos_database:
  language: python
lib/py_dev_dependencies:
  language: python
lib/py_edge_device:
  language: python
lib/py_edge_interface:
  language: python
lib/py_edge_server:
  language: python
lib/py_monorepo_manager:
  language: python
  makefile:
    boilerplate:
    - poetry run monorepo_manager all
services/api:
  custom_ci_steps:
    post_test_steps:
    - if: ${{ !cancelled() }}
      name: Set up - Install node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - if: ${{ !cancelled() }}
      name: Set up - Install yarn
      run: corepack enable && yarn set version classic
    - if: ${{ !cancelled() }}
      name: Set up - Cache dependencies
      uses: actions/cache@v4
      with:
        key: backend-codegen-lock-${{ hashFiles('./yarn.lock') }}
        path: ./**/node_modules/*
    - if: ${{ !cancelled() }}
      name: Set up - Install codegen dependencies
      run: yarn install --immutable
    - if: ${{ !cancelled() }}
      name: Generate - backend openapi spec and client code
      run: make api-openapi
  language: python
services/device:
  language: python
  makefile:
    config:
    - poetry run python -m device.cli config create
    config-show:
    - poetry run python -m device.cli config show
    run:
    - poetry run python -m device.cli run
services/frontend:
  language: javascript
services/nginx:
  language: binary
