name: carlos

services:

  api:
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    restart: unless-stopped
    environment:
      - API_CORS_ORIGINS=${API_CORS_ORIGINS}
      # Auth0
      - AUTH0_TENANT_ID=${AUTH0_TENANT_ID}
      - AUTH0_REGION=${AUTH0_REGION}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      # Database
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    depends_on:
      - db
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  frontend:
    build:
      context: .
      dockerfile: ./services/frontend/Dockerfile
    restart: unless-stopped
    environment:
      - VITE_APP_API_URL=http://localhost/api
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - 80:80
    volumes:
      - ./services/nginx/templates-dev:/etc/nginx/templates:ro

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_NAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: