version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    environment:
      - DOMAIN
    ports:
      - 80:80
    volumes:
      - ./services/nginx/templates-initiate:/etc/nginx/templates
      - ./.carlos_data/letsencrypt:/etc/letsencrypt
      - ./.carlos_data/certbot:/var/www/certbot
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >- 
             certonly --reinstall --webroot --webroot-path=/var/www/certbot
             --email ${EMAIL} --agree-tos --no-eff-email
             -d ${DOMAIN}
    volumes:
      - ./.carlos_data/letsencrypt:/etc/letsencrypt
      - ./.carlos_data/certbot:/var/www/certbot