site_name: Carlos
site_description: Your friendly greenhouse manager.
site_url: https://fanghanel.dev/carlos

theme:
  name: material
  logo: assets/type-white.png
  favicon: assets/favicon.png
  palette:
    primary: light green
    accent: green

extra_css:
  - stylesheets/extra.css