site_name: Carlos
site_description: Your friendly greenhouse manager.
site_url: https://fanghanel.dev/carlos

theme:
  name: material
  logo: assets/carlos-logo-type.png
  favicon: assets/favicon.png
  palette:
    primary: carlos
    accent: carlos
    scheme: slate

extra_css:
  - stylesheets/extra.css
  - stylesheets/carlos.css