site_name: Carlos
site_description: Your friendly greenhouse manager.
site_url: https://fanghanel.dev/carlos


theme:
  name: material
  logo: _assets/carlos-logo-type.png
  favicon: _assets/favicon.png
  palette:
    primary: carlos
    accent: carlos
    scheme: slate
  features:
    - content.code.annotate
    - content.code.copy
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.path

extra_css:
  - _stylesheets/extra.css
  - _stylesheets/carlos.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences