name: deploy-server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      # https://blog.benoitblanchon.fr/github-action-run-ssh-commands/
      - name: Configure SSH on host
        run: |
          mkdir -p ~/.ssh/
          echo "$KEY" > ~/.ssh/carlos.key
          chmod 600 ~/.ssh/carlos.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $HOST
            User $USER
            IdentityFile ~/.ssh/carlos.key
            StrictHostKeyChecking no
          END
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          KEY: ${{ secrets.KEY }}
      - name: Update the server
        run: ssh staging 'sh /carlos/scripts/server-update.sh'